name=Adafruit ST7735 and ST7789 Library WITHOUT SD
version=1.11.0
author=Adafruit_KRZHU_FIX
maintainer=Adafruit <info@adafruit.com>
sentence=This is a library for the Adafruit ST7735, ST7789, ST7796S SPI displays.
paragraph=This is a library for the Adafruit ST7735, ST7789, ST7796S SPI displays.
category=Display
url=
architectures=*
depends=Adafruit GFX Library, Adafruit seesaw Library
